[deps]
ApplicationDrivenLearning = "0856f1c8-ef17-4e14-9230-2773e47a789e"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
